// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe7_UbXrdcpQhuf2vk_-brsmBCRJYjzwU',
    appId: '1:686750351871:web:a14bce65bca14ede1f27ca',
    messagingSenderId: '686750351871',
    projectId: 'fir-provider-362ad',
    authDomain: 'fir-provider-362ad.firebaseapp.com',
    storageBucket: 'fir-provider-362ad.firebasestorage.app',
    measurementId: 'G-5QYTNL4KN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChsEK3tSQaCYMmbqfd91uriBn9VyUi1X0',
    appId: '1:686750351871:android:c3206d4f677257f11f27ca',
    messagingSenderId: '686750351871',
    projectId: 'fir-provider-362ad',
    storageBucket: 'fir-provider-362ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDcP5PllfXFz5bKo1tQfM8rJZ0UHDw7RY',
    appId: '1:686750351871:ios:7237303fba702ce41f27ca',
    messagingSenderId: '686750351871',
    projectId: 'fir-provider-362ad',
    storageBucket: 'fir-provider-362ad.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDcP5PllfXFz5bKo1tQfM8rJZ0UHDw7RY',
    appId: '1:686750351871:ios:7237303fba702ce41f27ca',
    messagingSenderId: '686750351871',
    projectId: 'fir-provider-362ad',
    storageBucket: 'fir-provider-362ad.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe7_UbXrdcpQhuf2vk_-brsmBCRJYjzwU',
    appId: '1:686750351871:web:435387d16c3eb0fa1f27ca',
    messagingSenderId: '686750351871',
    projectId: 'fir-provider-362ad',
    authDomain: 'fir-provider-362ad.firebaseapp.com',
    storageBucket: 'fir-provider-362ad.firebasestorage.app',
    measurementId: 'G-YMZGBT0C8F',
  );
}
