// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_spyTHwSgpoj9Mso86ah5mw__A3WUrow',
    appId: '1:451535222688:web:06590ae59f544f558816c5',
    messagingSenderId: '451535222688',
    projectId: 'fir-demo-86a10',
    authDomain: 'fir-demo-86a10.firebaseapp.com',
    storageBucket: 'fir-demo-86a10.firebasestorage.app',
    measurementId: 'G-L6XEF1HTW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9eRiOzt45f3ibrxFBn7eWyHJJEx0UGNk',
    appId: '1:451535222688:android:8e6301fbf5423a448816c5',
    messagingSenderId: '451535222688',
    projectId: 'fir-demo-86a10',
    storageBucket: 'fir-demo-86a10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3k5vbWdbxRygqn90L6TBKXvf7PAPOCWI',
    appId: '1:451535222688:ios:145a65240e6e40948816c5',
    messagingSenderId: '451535222688',
    projectId: 'fir-demo-86a10',
    storageBucket: 'fir-demo-86a10.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3k5vbWdbxRygqn90L6TBKXvf7PAPOCWI',
    appId: '1:451535222688:ios:145a65240e6e40948816c5',
    messagingSenderId: '451535222688',
    projectId: 'fir-demo-86a10',
    storageBucket: 'fir-demo-86a10.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_spyTHwSgpoj9Mso86ah5mw__A3WUrow',
    appId: '1:451535222688:web:a0839fd6cc403e758816c5',
    messagingSenderId: '451535222688',
    projectId: 'fir-demo-86a10',
    authDomain: 'fir-demo-86a10.firebaseapp.com',
    storageBucket: 'fir-demo-86a10.firebasestorage.app',
    measurementId: 'G-B0VRP3CN0C',
  );
}
